import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const targetPath = path.join(root, ".env");
const force = process.argv.includes("--force");

if (fs.existsSync(targetPath) && !force) {
  console.log(".env already exists; nothing changed. Use --force to recreate it.");
  process.exit(0);
}

const databasePassword = crypto.randomBytes(18).toString("hex");
const jwtSecret = crypto.randomBytes(48).toString("base64url");
const encryptionKey = crypto.randomBytes(32).toString("hex");
const adminPassword = `Vvk@${crypto.randomBytes(12).toString("base64url")}9`;

const content = `# Generated by npm run setup:env
ADMISSION_YEAR="2026"

POSTGRES_USER="vvk_app"
POSTGRES_PASSWORD="${databasePassword}"
POSTGRES_DB="vvk_2026_2027"
DATABASE_URL="postgresql://vvk_app:${databasePassword}@localhost:5433/vvk_2026_2027?schema=public"

REDIS_URL="redis://localhost:6380"

JWT_SECRET="${jwtSecret}"
ENCRYPTION_KEY="${encryptionKey}"
CCCD_EXCEPTION_LIST=""

ADMIN_INITIAL_USERNAME="admin"
ADMIN_INITIAL_PASSWORD="${adminPassword}"

STORAGE_ROOT="./storage"
`;

fs.writeFileSync(targetPath, content, { encoding: "utf8", flag: "w" });
console.log("Created .env successfully.");
console.log("Initial admin username: admin");
console.log(`Initial admin password: ${adminPassword}`);
console.log("Store this password securely and change it after the first login.");
